image: Visual Studio 2017

platform:
- x64

cache:
- node_modules
- '%USERPROFILE%\.electron'

init:
- git config --global core.autocrlf input

install:
- ps: Install-Product node 8 x64
- yarn

build_script:
- yarn run webpack
- yarn run build

after_build:
- 7z a euralis_volailles_productions.zip dist\


test: off

artifacts:
- path: euralis_volailles_productions.zip
  name: euralis_volailles_productions

deploy:
 release: euralis_volailles_productions-v$(appveyor_build_version)
 description: 'Release description'
 provider: GitHub
 auth_token:
   secure: 608d343489808fe3e2ad6d5751a09b3a50108bed # your encrypted token from GitHub
 artifact: /.*\.zip/            # upload all NuGet packages to release assets
 draft: false
 prerelease: false
 on:
   branch: master                 # release from master branch only
   appveyor_repo_tag: true        # deploy on tag push only