image: Visual Studio 2017

platform:
  - x64
  - ia32

cache:
  - node_modules
  - '%USERPROFILE%\.electron'

init:
  - git config --global core.autocrlf input

install:
  - ps: Install-Product node 8 x64
  - yarn

build_script:
  - yarn run rebuild
  - yarn run webpack
  - yarn run release-win

test: off

deploy:
  - provider: GitHub
    - auth_token:
    - secure: 85af0df0cb59650e4591dbbce52439b02faf6a69
  - artifact: dist\*
  - draft: true
  - prerelease: false
  - on:
    - appveyor_repo_tag: true