version: 1.0.{build}

image: Visual Studio 2017

environment:
  nodejs_version: "10.19.0"
  GH_TOKEN:
    secure: v/vMjewDvp+qnq0z3RaGeEZNYcdb92gVEmG3Kimwm/WMeu2Zw5fucTQqNjiKWlYc

platform:
  - x64

cache:
  - node_modules
  - '%USERPROFILE%\.electron'

init:
  - git config --global core.autocrlf input

install:
  - ps: Install-Product node $env:nodejs_version
  - yarn

build_script:
  - yarn build:electron:prod

deploy_script:
  - IF DEFINED APPVEYOR_REPO_TAG_NAME (yarn release --publish onTagOrDraft)

test: off
