image: Visual Studio 2017

environment:
  nodejs_version: "9.11.1"

platform:
  - x64

cache:
  - node_modules
  - '%USERPROFILE%\.electron'

init:
  - git config --global core.autocrlf input

install:
  - ps: Install-Product node $env:nodejs_version
  - npm i

build_script:
  - npm run release

after_build:
  - 7z a euralis_volailles_productions.zip dist\


test: off

artifacts:
  - path: euralis_volailles_productions.zip
    name: euralis_volailles_productions

deploy:

  - provider: GitHub
    artifact: /.*\.zip/
    draft: false
    prerelease: false
    on:
      branch: master
      appveyor_repo_tag: true
